--- 
  - name: deploy java application 1 jenkins.war
    get_url:
      url: https://updates.jenkins.io/download/war/2.511/jenkins.war
      dest: /opt/tomcat/webapps/jenkins.war
      force_basic_auth: yes
  
  - name: deploy java application 2 mahaLogin.war
    get_url:
      url: https://javaapp22may25.s3.ap-south-1.amazonaws.com/mahaLogin.war
      dest: /opt/tomcat/webapps/mahaLogin.war
      force_basic_auth: yes